"use client";
import { useState } from "react";

const steps = [
  ["01", "看见自己", "将经历、兴趣与偏好转化为可理解的能力证据。"],
  ["02", "读懂岗位", "从 JD 的字里行间，识别真实的能力和工作环境要求。"],
  ["03", "做出选择", "用匹配点、能力缺口和行动路径，支持下一步决策。"],
];
const traits = ["探索型思维", "问题拆解", "系统优化", "主动学习"];

export default function Home() {
 const [nav, setNav] = useState("产品介绍");
 const [screen, setScreen] = useState<"home" | "assessment" | "report" | "jd" | "match" | "case">("home");
 const [step, setStep] = useState(0); const [submitted, setSubmitted] = useState(false);
 const [jd, setJd] = useState("");
 const navs: [string, typeof screen][] = [["产品介绍","home"],["能力画像","report"],["JD 洞察","jd"],["匹配报告","match"],["Case Study","case"]];
 const go=(name:string, page:typeof screen)=>{setNav(name);setScreen(page); window.scrollTo({top:0,behavior:"smooth"})};
 return <main>
   <header><a className="brand" onClick={()=>go("产品介绍","home")}><i/>CAREER INSIGHT <em>AI</em></a><nav>{navs.map(([n,p])=><button key={n} className={nav===n?"active":""} onClick={()=>go(n,p)}>{n}</button>)}</nav><button className="small-cta" onClick={()=>{setScreen("assessment");setNav("开始分析")}}>开始分析 <span>↗</span></button></header>
   {screen==="home" && <>
    <section className="hero"><div className="eyebrow">CAREER DECISION INTELLIGENCE <b>•</b> 01 — 06</div><div className="hero-grid"><div><p className="intro">不是找到一份工作，<br/>而是找到<span>适合你的工作方式。</span></p><p className="sub">Career Insight AI 帮你理解能力特点，读懂岗位背后的真实要求，并以清晰证据支持下一次职业选择。</p><div className="actions"><button className="primary" onClick={()=>{setScreen("assessment");setNav("开始分析")}}>开始职业分析 <span>→</span></button><button className="text-btn" onClick={()=>go("能力画像","report")}>查看示例报告 <span>↓</span></button></div></div><div className="hero-art"><div className="orbit one"/><div className="orbit two"/><div className="axis"/><div className="node n1">A</div><div className="node n2">I</div><div className="node n3">C</div><div className="insight-card"><small>YOUR CAREER SIGNAL</small><strong>86</strong><span>Insight clarity score</span><div className="mini-line"/></div><p>EXPLORE<br/><b>WITH</b><br/>INTENT</p></div></div><div className="hero-foot"><span>为学生与职场新人设计</span><span>01 / 以证据为起点</span><span>02 / 不止于岗位推荐</span></div></section>
    <section className="problem"><div className="section-tag">THE DECISION GAP / 01</div><h2>职业选择的难点，<br/>往往不是<span>选择太少。</span></h2><div className="problem-grid"><p>我们知道很多岗位名称，却很少真正理解：它们每天需要怎样工作、怎样的人能持续做好。</p><p>Career Insight 将模糊的“适不适合”，转化为可被验证、理解和行动的职业判断。</p></div></section>
    <section className="how"><div className="section-tag">HOW IT WORKS / 02</div><div className="steps">{steps.map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><div className="arrow">↘</div></article>)}</div></section>
    <section className="sample"><div><div className="section-tag">A CLEARER NEXT STEP / 03</div><h2>每一份洞察，<br/>都应该通向行动。</h2><button className="primary" onClick={()=>go("匹配报告","match")}>探索匹配报告 <span>→</span></button></div><div className="sample-card"><div className="card-top"><span>CAREER INSIGHT REPORT</span><b>2026.07</b></div><h3>林然的职业<br/>能力画像</h3><div className="profile-row"><div className="avatar">林</div><div><small>核心能力倾向</small><p>分析 · 探索 · 系统优化</p></div></div><div className="bars"><i/><i/><i/><i/></div><div className="card-bottom">VIEW THE FULL REPORT <span>→</span></div></div></section>
   </>}
   {screen==="assessment" && <Assessment step={step} setStep={setStep} submitted={submitted} setSubmitted={setSubmitted} onReport={()=>go("能力画像","report")}/>}
   {screen==="report" && <Profile onJD={()=>go("JD 洞察","jd")}/>}
   {screen==="jd" && <JD jd={jd} setJd={setJd} onMatch={()=>go("匹配报告","match")}/>}
   {screen==="match" && <Match onCase={()=>go("Case Study","case")}/>}
   {screen==="case" && <Case/>}
   <footer><a className="brand"><i/>CAREER INSIGHT <em>AI</em></a><span>Designed as a product thinking case study.</span><span>© 2026</span></footer>
 </main>
}

function Assessment({step,setStep,submitted,setSubmitted,onReport}:{step:number,setStep:(x:number)=>void,submitted:boolean,setSubmitted:(x:boolean)=>void,onReport:()=>void}){const data=[{k:"01",t:"个人背景",d:"让我们从你已经走过的路径开始。",qs:["姓名","专业 / 研究方向","目前阶段"]},{k:"02",t:"行为模式",d:"没有标准答案，请选择更像你的那一个。",qs:["你最容易沉浸在哪类事情？","面对陌生问题时，你通常？"]},{k:"03",t:"工作偏好",d:"了解你能够持续投入的工作环境。",qs:["你更偏好的工作节奏？","你倾向于怎样推进工作？"]},{k:"04",t:"职业价值观",d:"请按重要程度，排出最关注的三个。",qs:["你希望工作首先带来什么？"]}][step]; const opts=["研究复杂问题","创造新的东西","与人交流协调","优化已有流程","收集信息寻找规律"];return <section className="assessment"><div className="report-top"><span>CAREER INSIGHT / ASSESSMENT</span><span>{data.k} — 04</span></div>{submitted?<div className="complete"><div className="check">✓</div><div className="section-tag">ANALYSIS READY</div><h1>你的能力画像<br/>已经准备好了。</h1><p>我们已将你的经历、行为模式与工作偏好转化为一份清晰的职业洞察。</p><button className="primary" onClick={onReport}>阅读能力画像 <span>→</span></button></div>:<div className="form"><aside><small>职业分析问卷</small><div className="progress"><i style={{height:`${(step+1)*25}%`}}/></div><span>{data.k}</span></aside><div className="form-content"><div className="section-tag">MODULE {data.k}</div><h1>{data.t}</h1><p>{data.d}</p>{data.qs.map((q,i)=><div className="question" key={q}><label>{q}</label>{step===0?<input placeholder={i===0?"例如：林然":"请填写你的回答"}/>:step===3?<div className="value-options">{["成长", "创造性", "自主性", "稳定", "收入", "社会价值"].map((x,n)=><button key={x}><b>{n+1}</b>{x}</button>)}</div>:<div className="options">{opts.slice(0,i?4:5).map(x=><button key={x}>{x}<span>+</span></button>)}</div>}</div>)}<div className="form-actions"><button className="text-btn" disabled={!step} onClick={()=>setStep(step-1)}>← 上一步</button><button className="primary" onClick={()=>step===3?setSubmitted(true):setStep(step+1)}>{step===3?"生成能力画像":"下一步"} <span>→</span></button></div></div></div>}</section>}

function Profile({onJD}:{onJD:()=>void}){return <section className="report"><div className="report-top"><span>CAREER INSIGHT REPORT</span><span>PERSONAL EDITION / 2026</span></div><div className="cover"><div><div className="section-tag">01 / PERSONAL CAPABILITY PORTRAIT</div><p className="cover-label">林然的</p><h1>职业能力<br/><em>画像报告</em></h1><p>基于个人经历、兴趣与能力倾向的职业分析报告</p></div><div className="cover-mark">CI<br/><span>AI</span></div></div><div className="portrait"><div><div className="section-tag">02 / THE WAY YOU WORK</div><h2>你是一位<br/><span>从问题出发的探索者。</span></h2><p>你习惯通过拆解问题、收集信息和建立框架来形成判断。比起快速给出结论，你更在意找到问题背后的逻辑。</p></div><div className="trait-list">{traits.map((t,i)=><div key={t}><b>0{i+1}</b><span>{t}</span><i/></div>)}</div></div><div className="capabilities"><div className="section-tag">03 / CORE CAPABILITIES</div><h2>能力不是抽象评分，<br/>而是你反复展现的行为。</h2><div className="cap-grid"><Radar/><div className="evidence">{[["问题分析能力","86","善于从复杂现象中梳理关键变量，并建立清晰的分析框架。"],["学习能力","82","在陌生领域能主动检索信息，快速建立基础认知。"],["沟通协调能力","74","具备倾听与转译能力，正在积累推动他人的经验。"]].map(x=><article key={x[0]}><div><span>{x[0]}</span><b>{x[1]}</b></div><p>{x[2]}</p><small>证据：项目复盘 · 校园运营经历</small></article>)}</div></div></div><div className="risk"><div className="section-tag">04 / GROWTH EDGES</div><h2>保持探索，也要<br/>练习<span>持续抵达。</span></h2><div><article><b>01</b><h3>兴趣范围较广</h3><p>你对新领域保持好奇，建议选择一个方向完成 3–6 个月的连续积累。</p></article><article><b>02</b><h3>执行规划待强化</h3><p>面对开放问题时，尝试用阶段目标和截止日期把思考推向落地。</p></article></div></div><div className="directions"><div className="section-tag">05 / POSSIBLE DIRECTIONS</div><h2>值得进一步验证的<br/>职业方向。</h2>{[["产品经理","88%","洞察用户、拆解需求、协调推进，与你的能力组合高度呼应。"],["战略与业务分析","82%","适合用结构化分析理解业务问题，并将洞察转成建议。"],["数字化运营","76%","可发挥数据敏感度与流程优化倾向，积累业务理解。"]].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><strong>{x[1]}</strong><p>{x[2]}</p><span>匹配度</span></article>)}<button className="primary" onClick={onJD}>分析目标岗位 JD <span>→</span></button></div></section>}

function Radar(){return <div className="radar"><div className="radar-shape"/><span className="r1">问题分析<br/><b>86</b></span><span className="r2">学习能力<br/><b>82</b></span><span className="r3">用户洞察<br/><b>78</b></span><span className="r4">沟通协调<br/><b>74</b></span><span className="r5">创造能力<br/><b>71</b></span><span className="r6">执行能力<br/><b>69</b></span></div>}

function JD({jd,setJd,onMatch}:{jd:string,setJd:(v:string)=>void,onMatch:()=>void}){const [done,setDone]=useState(false);const environment:[string,number][]=[["沟通频率",5],["变化程度",5],["自主程度",4],["流程规范",3]];return <section className="jd"><div className="section-tag">JD INSIGHT / 01</div><h1>读懂岗位，<br/><span>不止读懂职责。</span></h1><p>一段 JD 不只说明“要做什么”，也暗示了岗位真实的节奏、协作方式与挑战。</p><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="粘贴目标岗位 JD，或使用示例内容…"/><div className="jd-actions"><button className="text-btn" onClick={()=>setJd("负责产品需求调研、方案设计与项目推进；与研发、设计和运营团队保持高频协作，持续跟踪数据并优化产品体验。")}>填入产品经理示例</button><button className="primary" onClick={()=>setDone(true)}>开始解析 <span>→</span></button></div>{done&&<div className="jd-result"><div className="result-title"><span>ANALYSIS COMPLETE</span><b>产品经理 / 通用方向</b></div><div className="jd-columns"><article><small>01 / 核心能力要求</small>{["用户研究与需求判断","跨团队沟通与推进","数据意识与复盘能力","产品方案表达"].map((x,i)=><p key={x}><b>0{i+1}</b>{x}</p>)}</article><article><small>02 / 隐性工作环境</small>{environment.map(x=><div className="meter" key={x[0]}><span>{x[0]}</span><i>{"●".repeat(x[1])}<em>{"○".repeat(5-x[1])}</em></i></div>)}</article><article><small>03 / 真实工作模式</small><div className="donut">40<small>%</small></div><p className="work-copy">需求沟通是日常重心，其次是项目推进与数据分析。</p><button className="text-btn" onClick={onMatch}>查看与你的匹配 →</button></article></div></div>}</section>}

function Match({onCase}:{onCase:()=>void}){return <section className="match"><div className="section-tag">FIT ANALYSIS / PRODUCT MANAGER</div><div className="match-hero"><div><h1>你与这个岗位，<br/><span>有清晰的交集。</span></h1><p>匹配度不是结论，而是一张帮助你识别优势与下一步的地图。</p></div><div className="score"><b>85</b><span>%</span><small>综合匹配度</small></div></div><div className="fit-section"><small>ADVANTAGE MATCH / 01</small><h2>已经具备的<br/>优势信号</h2>{[["用户洞察能力","运营校园账号，根据 200+ 条反馈持续优化内容主题与发布节奏。","JD 需要理解用户，发现真实需求"],["问题分析能力","在课程项目中负责梳理用户旅程，定位转化流失环节。","JD 需要从模糊信息中拆解问题"],["学习与适应能力","主动学习 Figma 与基础数据分析，独立完成验证方案。","岗位环境变化快，需要快速建立认知"]].map((x,i)=><article className="fit-row" key={x[0]}><b>0{i+1}</b><div><h3>{x[0]}</h3><p>{x[1]}</p></div><div className="jd-need"><small>JD 要求</small><p>{x[2]}</p></div><strong>★★★★★</strong></article>)}</div><div className="gap"><small>GROWTH OPPORTUNITIES / 02</small><h2>让优势成为<br/><span>更强的职业筹码。</span></h2><div className="gap-grid"><article><b>SQL 数据分析</b><p>当前缺少相关项目证据。用一个真实数据集完成从提问、分析到汇报的闭环。</p><span>建议周期：4 周</span></article><article><b>项目推进</b><p>已有协作经验，可尝试主动承担小项目的排期、风险同步和复盘职责。</p><span>建议周期：持续练习</span></article></div></div><div className="next"><div><small>NEXT STEP / 03</small><h2>接下来，做一件<br/>可以被看见的事。</h2><p>选择一个小而真实的问题，完成一次有证据的产品实践。它会成为你下一次表达能力的底气。</p></div><button className="primary" onClick={onCase}>查看产品设计思考 <span>→</span></button></div></section>}

function Case(){return <section className="case"><div className="case-hero"><div className="section-tag">PRODUCT CASE STUDY</div><p>Career Insight AI</p><h1>把“适合”变成<br/><span>可以讨论的证据。</span></h1><small>个人作品集 / 2026</small></div><div className="case-grid">{[["01","项目背景","学生与职场新人常在岗位名称与真实工作之间迷失。信息很多，判断依据却很少。"],["02","用户痛点","不知道自己擅长什么；看不懂 JD 的隐性要求；缺少把差距转化为行动的方法。"],["03","产品方案","以个人画像、JD 洞察和人岗匹配三段式流程，帮助用户建立职业决策的证据链。"],["04","设计原则","不做人格测试；不替用户做决定；每一个判断都关联到经历、行为和可行动建议。"],["05","关键功能","行为型问卷、咨询报告式画像、JD 工作环境推断、能力证据匹配与成长路线。"],["06","未来迭代","接入 AI 个性化分析；支持多岗位对比；加入职业访谈、作品集与长期成长追踪。"]].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div></section>}
