"use client";
import { useState } from "react";

const steps = [
  ["01", "看见自己", "将经历、兴趣与偏好转化为可理解的能力证据。"],
  ["02", "读懂岗位", "从 JD 的字里行间，识别真实的能力和工作环境要求。"],
  ["03", "做出选择", "用匹配点、能力缺口和行动路径，支持下一步决策。"],
];
const traits = ["探索型思维", "问题拆解", "系统优化", "主动学习"];

type ProfileResult = {summary:string;traits:string[];capabilities:Array<{name:string;score:number;level:string;reason:string;evidence:string[]}>;risks:Array<{title:string;description:string;suggestion:string}>;directions:Array<{name:string;match:number;reason:string}>};
type JDResult = {jobTitle:string;coreRequirements:Array<{name:string;importance:number;evidence:string}>;environment:Array<{name:string;score:number;interpretation:string}>;workModes:Array<{name:string;percentage:number}>;hiddenSignals:Array<{signal:string;meaning:string}>};
type MatchResult = {overallScore:number;summary:string;strengths:Array<{requirement:string;evidence:string;score:number;reason:string}>;gaps:Array<{requirement:string;currentState:string;suggestion:string;priority:string}>;actionPlan:Array<{period:string;action:string;output:string}>};
const demoProfile:ProfileResult={summary:"你习惯通过拆解问题、收集信息和建立框架来形成判断。比起快速给出结论，你更在意找到问题背后的逻辑。",traits,capabilities:[{name:"问题分析能力",score:86,level:"高",reason:"善于从复杂现象中梳理关键变量，并建立清晰的分析框架。",evidence:["项目复盘","校园运营经历"]},{name:"学习能力",score:82,level:"高",reason:"在陌生领域能主动检索信息，快速建立基础认知。",evidence:["自主学习经历"]},{name:"沟通协调能力",score:74,level:"中",reason:"具备倾听与转译能力，正在积累推动他人的经验。",evidence:["协作项目"]}],risks:[{title:"兴趣范围较广",description:"你对新领域保持好奇。",suggestion:"选择一个方向完成3–6个月连续积累。"},{title:"执行规划待强化",description:"面对开放问题时可能投入较多分析时间。",suggestion:"用阶段目标和截止日期把思考推向落地。"}],directions:[{name:"产品经理",match:88,reason:"洞察用户、拆解需求、协调推进，与你的能力组合高度呼应。"},{name:"战略与业务分析",match:82,reason:"适合用结构化分析理解业务问题，并将洞察转成建议。"},{name:"数字化运营",match:76,reason:"可发挥数据敏感度与流程优化倾向，积累业务理解。"}]};

async function runAnalysis<T>(action:"profile"|"jd"|"match", payload:unknown, accessCode:string):Promise<T>{
 const response=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json","x-career-access-code":accessCode},body:JSON.stringify({action,payload})});
 const result=await response.json() as {data?:T;error?:string};
 if(!response.ok||!result.data) throw new Error(result.error||"分析失败，请稍后重试。");
 return result.data;
}

export default function Home() {
 const [nav, setNav] = useState("产品介绍");
 const [screen, setScreen] = useState<"home" | "assessment" | "report" | "jd" | "match" | "case">("home");
 const [step, setStep] = useState(0); const [submitted, setSubmitted] = useState(false);
 const [jd, setJd] = useState("");
 const [accessCode,setAccessCode]=useState("");
 const [profileResult,setProfileResult]=useState<ProfileResult|null>(null);
 const [jdResult,setJdResult]=useState<JDResult|null>(null);
 const [matchResult,setMatchResult]=useState<MatchResult|null>(null);
 const navs: [string, typeof screen][] = [["产品介绍","home"],["能力画像","report"],["JD 洞察","jd"],["匹配报告","match"],["Case Study","case"]];
 const go=(name:string, page:typeof screen)=>{setNav(name);setScreen(page); window.scrollTo({top:0,behavior:"smooth"})};
 return <main>
   <header><a className="brand" onClick={()=>go("产品介绍","home")}><i/>CAREER INSIGHT <em>AI</em></a><nav>{navs.map(([n,p])=><button key={n} className={nav===n?"active":""} onClick={()=>go(n,p)}>{n}</button>)}</nav><button className="small-cta" onClick={()=>{setScreen("assessment");setNav("开始分析")}}>开始分析 <span>↗</span></button></header>
   {screen==="home" && <>
    <section className="hero"><div className="eyebrow">CAREER DECISION INTELLIGENCE <b>•</b> 01 — 06</div><div className="hero-grid"><div><p className="intro">不是找到一份工作，<br/>而是找到<span>适合你的工作方式。</span></p><p className="sub">Career Insight AI 帮你理解能力特点，读懂岗位背后的真实要求，并以清晰证据支持下一次职业选择。</p><div className="actions"><button className="primary" onClick={()=>{setScreen("assessment");setNav("开始分析")}}>开始职业分析 <span>→</span></button><button className="text-btn" onClick={()=>go("能力画像","report")}>查看示例报告 <span>↓</span></button></div></div><div className="hero-art"><div className="orbit one"/><div className="orbit two"/><div className="axis"/><div className="node n1">A</div><div className="node n2">I</div><div className="node n3">C</div><div className="insight-card"><small>YOUR CAREER SIGNAL</small><strong>86</strong><span>Insight clarity score</span><div className="mini-line"/></div><p>EXPLORE<br/><b>WITH</b><br/>INTENT</p></div></div><div className="hero-foot"><span>为学生与职场新人设计</span><span>01 / 以证据为起点</span><span>02 / 不止于岗位推荐</span></div></section>
    <section className="problem"><div className="section-tag">THE DECISION GAP / 01</div><h2>职业选择的难点，<br/>往往不是<span>选择太少。</span></h2><div className="problem-grid"><p>我们知道很多岗位名称，却很少真正理解：它们每天需要怎样工作、怎样的人能持续做好。</p><p>Career Insight 将模糊的“适不适合”，转化为可被验证、理解和行动的职业判断。</p></div></section>
    <section className="how"><div className="section-tag">HOW IT WORKS / 02</div><div className="steps">{steps.map(s=><article key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><div className="arrow">↘</div></article>)}</div></section>
    <section className="sample"><div><div className="section-tag">A CLEARER NEXT STEP / 03</div><h2>每一份洞察，<br/>都应该通向行动。</h2><button className="primary" onClick={()=>go("匹配报告","match")}>探索匹配报告 <span>→</span></button></div><div className="sample-card"><div className="card-top"><span>CAREER INSIGHT REPORT</span><b>2026.07</b></div><h3>你的职业<br/>能力画像</h3><div className="profile-row"><div className="avatar">你</div><div><small>你的核心能力倾向</small><p>分析 · 探索 · 系统优化</p></div></div><div className="bars"><i/><i/><i/><i/></div><div className="card-bottom">VIEW YOUR REPORT <span>→</span></div></div></section>
   </>}
   {screen==="assessment" && <Assessment step={step} setStep={setStep} submitted={submitted} setSubmitted={setSubmitted} accessCode={accessCode} setAccessCode={setAccessCode} onProfile={setProfileResult} onReport={()=>go("能力画像","report")}/>}
   {screen==="report" && <Profile data={profileResult} onJD={()=>go("JD 洞察","jd")}/>}
   {screen==="jd" && <JD jd={jd} setJd={setJd} data={jdResult} setData={setJdResult} accessCode={accessCode} setAccessCode={setAccessCode} profile={profileResult} onMatch={async()=>{const result=await runAnalysis<MatchResult>("match",{profile:profileResult||demoProfile,jd:jdResult},accessCode);setMatchResult(result);go("匹配报告","match")}}/>}
   {screen==="match" && <Match data={matchResult} onCase={()=>go("Case Study","case")}/>}
   {screen==="case" && <Case/>}
   <footer><a className="brand"><i/>CAREER INSIGHT <em>AI</em></a><span>Designed as a product thinking case study.</span><span>© 2026</span></footer>
 </main>
}

function Assessment({step,setStep,submitted,setSubmitted,accessCode,setAccessCode,onProfile,onReport}:{step:number;setStep:(x:number)=>void;submitted:boolean;setSubmitted:(x:boolean)=>void;accessCode:string;setAccessCode:(x:string)=>void;onProfile:(x:ProfileResult)=>void;onReport:()=>void}){
 const modules=[{k:"01",t:"个人背景",d:"让我们从你已经走过的路径开始。",qs:["姓名","专业 / 研究方向","经历与技能"]},{k:"02",t:"行为模式",d:"没有标准答案，请选择更像你的那一个。",qs:["你最容易沉浸在哪类事情？","面对陌生问题时，你通常？"]},{k:"03",t:"工作偏好",d:"了解你能够持续投入的工作环境。",qs:["你更偏好的工作节奏？","你倾向于怎样推进工作？"]},{k:"04",t:"职业价值观",d:"选择你最关注的三个。",qs:["你希望工作首先带来什么？"]}];
 const data=modules[step];
 const [answers,setAnswers]=useState<Record<string,string|string[]>>({});
 const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 const behaviorOptions=[["研究复杂问题","创造新的东西","与人交流协调","优化已有流程","收集信息寻找规律"],["搜集信息后分析","快速尝试解决","找别人讨论","建立系统方法"]];
 const preferenceOptions=[["稳定明确的工作","高变化、高探索的工作"],["独立深度工作","多人协作推进"]];
 const choose=(q:string,value:string,multiple=false)=>setAnswers(old=>{if(!multiple)return {...old,[q]:value};const list=Array.isArray(old[q])?old[q] as string[]:[];return {...old,[q]:list.includes(value)?list.filter(x=>x!==value):list.length<3?[...list,value]:list}});
 const submit=async()=>{setError("");if(!accessCode.trim()){setError("请输入站点所有者提供的体验码。");return}setLoading(true);try{const result=await runAnalysis<ProfileResult>("profile",{answers},accessCode.trim());onProfile(result);setSubmitted(true)}catch(e){setError(e instanceof Error?e.message:"分析失败，请重试。")}finally{setLoading(false)}};
 return <section className="assessment"><div className="report-top"><span>CAREER INSIGHT / ASSESSMENT</span><span>{data.k} — 04</span></div>{submitted?<div className="complete"><div className="check">✓</div><div className="section-tag">ANALYSIS READY</div><h1>你的能力画像<br/>已经准备好了。</h1><p>我们已将你的经历、行为模式与工作偏好转化为一份清晰的职业洞察。</p><button className="primary" onClick={onReport}>阅读你的能力画像 <span>→</span></button></div>:<div className="form"><aside><small>你的职业分析问卷</small><div className="progress"><i style={{height:`${(step+1)*25}%`}}/></div><span>{data.k}</span></aside><div className="form-content"><div className="section-tag">MODULE {data.k}</div><h1>{data.t}</h1><p>{data.d}</p>{data.qs.map((q,i)=><div className="question" key={q}><label>{q}</label>{step===0?<textarea className="short-input" value={(answers[q] as string)||""} onChange={e=>choose(q,e.target.value)} placeholder={i===0?"怎么称呼你？（选填）":i===1?"例如：市场营销 / 本科大四":"实习、项目、工作经历，以及你掌握的技能"}/>:step===3?<div className="value-options">{["成长","创造性","自主性","稳定","收入","社会价值"].map((x,n)=><button type="button" className={(answers[q] as string[]||[]).includes(x)?"selected":""} onClick={()=>choose(q,x,true)} key={x}><b>{n+1}</b>{x}</button>)}</div>:<div className="options">{(step===1?behaviorOptions[i]:preferenceOptions[i]).map(x=><button type="button" className={answers[q]===x?"selected":""} onClick={()=>choose(q,x)} key={x}>{x}<span>{answers[q]===x?"✓":"+"}</span></button>)}</div>}</div>)}{step===3&&<div className="question"><label>AI 体验码</label><input type="password" autoComplete="off" value={accessCode} onChange={e=>setAccessCode(e.target.value)} placeholder="由站点所有者提供，不是 API Key"/><small className="privacy-note">体验码只用于本次浏览，不会保存到 GitHub。</small></div>}{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button className="text-btn" disabled={!step||loading} onClick={()=>setStep(step-1)}>← 上一步</button><button className="primary" disabled={loading} onClick={()=>step===3?submit():setStep(step+1)}>{loading?"正在分析…":step===3?"生成你的能力画像":"下一步"} <span>→</span></button></div></div></div>}</section>
}

function Profile({data,onJD}:{data:ProfileResult|null;onJD:()=>void}){const d=data||demoProfile;return <section className="report"><div className="report-top"><span>YOUR CAREER INSIGHT REPORT</span><span>{data?"AI GENERATED":"SAMPLE REPORT"} / 2026</span></div><div className="cover"><div><div className="section-tag">01 / YOUR CAPABILITY PORTRAIT</div><p className="cover-label">为你生成的</p><h1>职业能力<br/><em>画像报告</em></h1><p>基于你的经历、兴趣与能力倾向生成</p></div><div className="cover-mark">CI<br/><span>AI</span></div></div><div className="portrait"><div><div className="section-tag">02 / THE WAY YOU WORK</div><h2>你的工作方式，<br/><span>正在形成清晰证据。</span></h2><p>{d.summary}</p></div><div className="trait-list">{d.traits.slice(0,4).map((t,i)=><div key={t}><b>0{i+1}</b><span>{t}</span><i/></div>)}</div></div><div className="capabilities"><div className="section-tag">03 / YOUR CORE CAPABILITIES</div><h2>能力不是抽象评分，<br/>而是你反复展现的行为。</h2><div className="cap-grid"><Radar data={d.capabilities}/><div className="evidence">{d.capabilities.slice(0,4).map(x=><article key={x.name}><div><span>{x.name}</span><b>{x.score}</b></div><p>{x.reason}</p><small>你的证据：{x.evidence?.join(" · ")||"当前信息不足"}</small></article>)}</div></div></div><div className="risk"><div className="section-tag">04 / YOUR GROWTH EDGES</div><h2>保持探索，也要<br/>练习<span>持续抵达。</span></h2><div>{d.risks.slice(0,2).map((x,i)=><article key={x.title}><b>0{i+1}</b><h3>{x.title}</h3><p>{x.description} {x.suggestion}</p></article>)}</div></div><div className="directions"><div className="section-tag">05 / YOUR POSSIBLE DIRECTIONS</div><h2>你值得进一步验证的<br/>职业方向。</h2>{d.directions.slice(0,3).map((x,i)=><article key={x.name}><b>0{i+1}</b><h3>{x.name}</h3><strong>{x.match}%</strong><p>{x.reason}</p><span>匹配度</span></article>)}<button className="primary" onClick={onJD}>分析你的目标岗位 JD <span>→</span></button></div></section>}

function Radar({data}:{data:Array<{name:string;score:number}>}){const items=data.slice(0,6);while(items.length<6)items.push({name:"待补充",score:0});return <div className="radar"><div className="radar-shape"/>{items.map((x,i)=><span className={`r${i+1}`} key={`${x.name}-${i}`}>{x.name.slice(0,6)}<br/><b>{x.score}</b></span>)}</div>}

function JD({jd,setJd,data,setData,accessCode,setAccessCode,profile,onMatch}:{jd:string;setJd:(v:string)=>void;data:JDResult|null;setData:(v:JDResult)=>void;accessCode:string;setAccessCode:(v:string)=>void;profile:ProfileResult|null;onMatch:()=>Promise<void>}){const [loading,setLoading]=useState(false);const [matching,setMatching]=useState(false);const [error,setError]=useState("");const analyze=async()=>{setError("");if(jd.trim().length<30){setError("请粘贴至少30个字的岗位JD。");return}if(!accessCode.trim()){setError("请输入体验码。");return}setLoading(true);try{setData(await runAnalysis<JDResult>("jd",{jd:jd.trim()},accessCode.trim()))}catch(e){setError(e instanceof Error?e.message:"解析失败，请重试。")}finally{setLoading(false)}};const match=async()=>{setError("");setMatching(true);try{await onMatch()}catch(e){setError(e instanceof Error?e.message:"匹配失败，请重试。")}finally{setMatching(false)}};return <section className="jd"><div className="section-tag">JD INSIGHT / 01</div><h1>读懂岗位，<br/><span>不止读懂职责。</span></h1><p>一段 JD 不只说明“要做什么”，也暗示了岗位真实的节奏、协作方式与挑战。</p><textarea value={jd} maxLength={10000} onChange={e=>setJd(e.target.value)} placeholder="粘贴目标岗位 JD，或使用示例内容…"/><div className="access-row"><input type="password" autoComplete="off" value={accessCode} onChange={e=>setAccessCode(e.target.value)} placeholder="输入 AI 体验码"/><small>API Key 只保存在 Cloudflare，这里填写的是体验码。</small></div>{error&&<p className="form-error">{error}</p>}<div className="jd-actions"><button className="text-btn" onClick={()=>setJd("负责产品需求调研、方案设计与项目推进；与研发、设计和运营团队保持高频协作，持续跟踪数据并优化产品体验。需要具备用户研究、数据分析与跨团队沟通能力。")}>填入产品经理示例</button><button className="primary" disabled={loading} onClick={analyze}>{loading?"正在解析…":"开始 AI 解析"} <span>→</span></button></div>{data&&<div className="jd-result"><div className="result-title"><span>AI ANALYSIS COMPLETE</span><b>{data.jobTitle}</b></div><div className="jd-columns"><article><small>01 / 核心能力要求</small>{data.coreRequirements.slice(0,5).map((x,i)=><p title={x.evidence} key={`${x.name}-${i}`}><b>0{i+1}</b>{x.name}</p>)}</article><article><small>02 / 隐性工作环境</small>{data.environment.slice(0,4).map(x=><div className="meter" title={x.interpretation} key={x.name}><span>{x.name}</span><i>{"●".repeat(Math.max(0,Math.min(5,x.score)))}<em>{"○".repeat(5-Math.max(0,Math.min(5,x.score)))}</em></i></div>)}</article><article><small>03 / 真实工作模式</small><div className="donut">{data.workModes[0]?.percentage||0}<small>%</small></div><p className="work-copy">{data.workModes.map(x=>`${x.name} ${x.percentage}%`).join(" · ")}</p><button className="text-btn" disabled={matching} onClick={match}>{matching?"正在生成匹配报告…":profile?"查看与你的匹配 →":"使用示例画像进行匹配 →"}</button></article></div></div>}</section>}

function Match({data,onCase}:{data:MatchResult|null;onCase:()=>void}){if(!data)return <section className="match"><div className="section-tag">FIT ANALYSIS</div><div className="complete"><h1>还没有生成<br/>AI 匹配报告。</h1><p>请先完成能力问卷并解析一份目标岗位 JD。</p></div></section>;return <section className="match"><div className="section-tag">FIT ANALYSIS / AI REPORT</div><div className="match-hero"><div><h1>你与这个岗位，<br/><span>有可以验证的交集。</span></h1><p>{data.summary}</p></div><div className="score"><b>{data.overallScore}</b><span>%</span><small>综合匹配度</small></div></div><div className="fit-section"><small>ADVANTAGE MATCH / 01</small><h2>已经具备的<br/>优势信号</h2>{data.strengths.map((x,i)=><article className="fit-row" key={`${x.requirement}-${i}`}><b>0{i+1}</b><div><h3>{x.requirement}</h3><p>{x.evidence}</p></div><div className="jd-need"><small>匹配解释</small><p>{x.reason}</p></div><strong>{"★".repeat(Math.max(1,Math.min(5,x.score)))}{"☆".repeat(5-Math.max(1,Math.min(5,x.score)))}</strong></article>)}</div><div className="gap"><small>GROWTH OPPORTUNITIES / 02</small><h2>让差距成为<br/><span>可以行动的路径。</span></h2><div className="gap-grid">{data.gaps.map(x=><article key={x.requirement}><b>{x.requirement}</b><p>{x.currentState} {x.suggestion}</p><span>优先级：{x.priority}</span></article>)}</div></div><div className="next"><div><small>NEXT STEP / 03</small><h2>接下来，做一件<br/>可以被看见的事。</h2>{data.actionPlan.map(x=><p key={x.period}><b>{x.period}</b>｜{x.action}；成果：{x.output}</p>)}</div><button className="primary" onClick={onCase}>查看产品设计思考 <span>→</span></button></div></section>}

function Case(){return <section className="case"><div className="case-hero"><div className="section-tag">PRODUCT CASE STUDY</div><p>Career Insight AI</p><h1>把“适合”变成<br/><span>可以讨论的证据。</span></h1><small>个人作品集 / 2026</small></div><div className="case-grid">{[["01","项目背景","学生与职场新人常在岗位名称与真实工作之间迷失。信息很多，判断依据却很少。"],["02","用户痛点","不知道自己擅长什么；看不懂 JD 的隐性要求；缺少把差距转化为行动的方法。"],["03","产品方案","以个人画像、JD 洞察和人岗匹配三段式流程，帮助用户建立职业决策的证据链。"],["04","设计原则","不做人格测试；不替用户做决定；每一个判断都关联到经历、行为和可行动建议。"],["05","关键功能","行为型问卷、咨询报告式画像、JD 工作环境推断、能力证据匹配与成长路线。"],["06","未来迭代","接入 AI 个性化分析；支持多岗位对比；加入职业访谈、作品集与长期成长追踪。"]].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div></section>}
